# Generated by Django 4.2.21 on 2025-05-20 15:49

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArieNaturala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_arie', models.CharField(max_length=200)),
                ('tip_arie', models.IntegerField(choices=[(0, 'Protejata'), (1, 'Neprotejata')])),
                ('judet_arie', models.CharField(max_length=200)),
                ('localitate_arie', models.CharField(max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Arii Naturale',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=200)),
                ('campanie_initiata_de', models.CharField(max_length=100)),
                ('text_petitie', ckeditor_uploader.fields.RichTextUploadingField()),
                ('arie_naturala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.arienaturala')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('adresa_email', models.EmailField(max_length=254)),
                ('judet', models.CharField(max_length=100)),
                ('numar_telefon', models.CharField(max_length=15)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.petition')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('arie_naturala', models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to='eenvironmentblog.arienaturala')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arie_discutie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.arienaturala')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DateSpeologice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('arie_naturala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.arienaturala')),
            ],
            options={
                'verbose_name_plural': 'Date Speologice',
            },
        ),
        migrations.CreateModel(
            name='DateHidrografice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('arie_naturala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.arienaturala')),
            ],
            options={
                'verbose_name_plural': 'Date Hidrografice',
            },
        ),
        migrations.CreateModel(
            name='DateGeografice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('arie_naturala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.arienaturala')),
            ],
            options={
                'verbose_name_plural': 'Date Geografice',
            },
        ),
        migrations.CreateModel(
            name='DateForestiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('arie_naturala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.arienaturala')),
            ],
            options={
                'verbose_name_plural': 'Date Forestiere',
            },
        ),
        migrations.CreateModel(
            name='DateBiodiversitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('arie_naturala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eenvironmentblog.arienaturala')),
            ],
            options={
                'verbose_name_plural': 'Date Biodiversitate',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eenvironmentblog.discussion')),
            ],
        ),
    ]
