# Generated by Django 4.2.21 on 2025-05-20 17:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eenvironmentblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arienaturala',
            name='descriere',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arienaturala',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='arii/'),
        ),
    ]
